---
title: "DataArt"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
library(dplyr); library(ggplot2); library(ggpubr);library(pabloverse)
```

Part of my practice includes experimentation with less conventional approaches in science communication and data visualization, and have explored different techniques such as:  [vid](https://vimeo.com/912795201).

# Data visualization

## 3D visualization and Augmented reality

<iframe src="https://player.vimeo.com/video/912795201?h=4da18dad9e" width="512" height="512" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>


# Creative coding

## Ray marching

Ray marching is a 3D modeling technique that I find really interesting. On brief, raymarching simulates a canvas where the pixels try to represent a 3 dimensional scene based on code. This technique can achieve some really interesting and abstract scenes. To me is trying to explain with code to a computer how to see the an imaginary landscape. Here are some examples of my work with Raymarching: 

<iframe src="https://player.vimeo.com/video/801443984?h=8a9dc0b790" width="512" height="512" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>

## Feedback 

## Celular automata

## Machine learning

# Data sonification

# Installation work

<iframe src="https://player.vimeo.com/video/951627400?h=4f64b73cff" width="512" height="512" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>

