---
title: "Herramientas Geostadisticas para Mapeo de enfermedades e Inferencia"
---

**Objetivo:** Proveer una vision general sobre las herramientas disponibles que podemos usar en geoestadistica para el mapeo de enfermedades e inferencia.  


# Introduccion:

De acurdo a la primera ley de geografia de Tobler, *"todo esta relacionado entre si, pero eventos que suceden cerca tienen mayor relacion comparados con eventos que suceden a mayor distancia"*. Este no siempre consideramos cuando realizamos inferencia estadistica, y para la mayoria de los metodos estadisticos (por ejemplo regression), asumimos que las observaciones fueron muestreadas de manera independiente.  
En este Workshop introduciremos, desde lo mas basico, a metodos para manipular y analizar datos espaciales. Con las tecnologías actuales, la cantidad de informacion disponeible puede ser un poco abrumadora cuando intentamos encontrar asociaciones entre dos o mas eventos. Existen muchos recursos que pueden ayudarnos a informar de mejor manera nuestros modelos estadisticos y obtener mas informacion de nuestros datos. Herramientas de libre acceso, tales como QGIS y `R`, ofrecen un medio muy flexible para manipular y analizar este tipo de datos.  
Para este workshop usaremos ejemplos en epidemiologia, el workshop esta orientado a entender conceptos en epidemiologia tales como asociacion, causalidad y confusion. Estos conceptos pueden ser aplicados a cualquier area en la que busquemos la asociacion entre dos o mas eventos.  

________

# Instructor

**Jose Pablo Gomez-Vazquez** (PhDc, MPVM, DVM), Universidad de California Davis. Pablo es un candidato de doctorado realizando su trabajo en el Center for Animal Disease Modeling and Surveillance de UC Davis. Sus intereses incluyen la aplicacion de teoria de redes y geoestadistica para informar politicas publicas y toma de decisiones en epidemiologia. Pablo ha trabajado con instituciones gubernamentales en Peru, Ecuador y California, proporcionando herramientas que pueden ser usadas en toma de decisiones.  

________


# Resultados de aprendizaje

  - Entender la estructura de datos espaciales (Vectores y Rasters)
  - Extraer y procesar datos espaciales
  - Inferencia estadistica para datos no espaciales
  - Correlacion e inferencia estadistica para datos espaciales
  - Visualizacion y presentacion de los resultados

________

# Estructura del curso:


## Modulo basico

  - Fundamentos de SIGs (QGIS)
    - Estructura de datos espaciales.  
    - Sistemas de coordenadas geograficas.  
  
  - Manipulacion de bases de datos en R:  
    - Operaciones con vectores.  
    - Operaciones con rasters.
    - Proyeccion y transformacion de los datos.  
    - Geocodificacion de datos.  
    - Limpieza y procesamiento de datos.  
  
  - Herramientas para visualizacion de datos
    - Visualizacion estatica y generacion de reportes.  
    - Visualizacion dinamica mediante videos, gifs y applicaciones web.  
  
  - Analisis de datos espaciales
    - Operaciones basadas en distancia  
    - Adjacencia.  
    - Autocorrelacion espacial.  
    - Clustering: Estadisticas globales y locales.  
    



# Horario

Este workshop puede ser ofrecido en diferentes formatos, anteriormente fue ofrecido como un workshop de 3 dias en los que se cubrieron temas desde lo mas basico de como usar `R` hasta inferencia geoestadistica con modelos de regression.  
El horario varia dependiendo del tiempo disponible y los conocimientos deseados de los participantes.  

________


# Antecedesntes y habilidades de los participantes

Este workshop esta diseñado para estudiantes y profesionistas interesados en estadistica y sistemas de informacion geograficos. Experiencia basica en estadistica y R son deseados, pero no necesarios. En el pasado, este workshop fue ofrecido para gente de la academia e instituciones gubernamentales.  
Para este workshop usaremos principalmente `R` y Rstudio, pero otras herramientas como QGIS y Google Earth tambien seran usadas con propositos de demostrar aplicaciones de los resultados.  

