---
title: "Jose Pablo Gomez-Vazquez"
output:
  pdf_document: 
  keep_tex: true
  includes:
        in_header: header.tex
  html_notebook: default
---

\begin{center}
DVM, MPVM, PhDc.  
  
website: https://jpablo91.github.io/
\end{center}


________________________
## Education: 



**PhD in Epidemiology** (2017-Current)  
*University of California Davis, California, United States*  
  

**Master in Preventive Veterinary Medicine** (2016-2017)  
*University of California Davis, California, United States*  
  

**Medicina Veterinaria y Zootecnia [Veterinary Medicine & Zootechnics]** (2010-2015)  
*UANL, Escobedo N.L., Mexico*  


________________________

## Profesional Experience:

#### Department of Veterinary Medicine and Epidemiology, University of California Davis. Davis, California, United States - Graduate Student Researcher
*June 2020 - Current*

#### Department of Population Health and Reproduction, University of California Davis. Davis, California, United States - Graduate Student Researcher
*August 2019 - June 2020*

#### One Health Institute, University of California Davis. Davis, California, United States - Graduate Student Researcher
*January 2018 - March 2018*
  
________________________

## Teaching Experience:

#### University of California Davis. Davis, California, United States - Teaching assistant on Spatial epidemiology (EPI 223)
*March 2019 - June 2019*


#### University of California Davis. Davis, California, United States - Teaching assistant on Mathematical Statistics (EPI 203)
*January 2019 - March 2019*

#### University of California Davis. Davis, California, United States - Teaching assistant on medical statistics (MPM 204)
*January 2018 - March 2019*

### Workhsops and training provided:

  - Análisis espacio-temporal de redes de contactos, UNAM, Mexico City, Mexico, November 19-20, 2019
  - Spatio-Temporal analysis of Movement Networks, Geovet 2019, Davis California, October 7, 2019
  - Herramientas geoestadisticas en epidemiologia, Agrocalidad, Quito, Pichincha, Ecuador, August 12-15, 2019
  - Analyzing Animal Health Spatial-explicit Networks Using R, UC Davis, Davis, California, February 6, 2019
  
________________________

## Publications:

  - **Gómez-Vázquez, J. P.**, Quevedo-Valle, M., Flores, U., Portilla Jarufe, K., & Martínez-López, B. (2019). Evaluation of the impact of live pig trade network, vaccination coverage and socio-economic factors in the classical swine fever eradication program in Peru. Preventive Veterinary Medicine, 162(May 2018), 29–37. https://doi.org/10.1016/j.prevetmed.2018.10.019
  
  - Garcia-Mazcorro JF, Castillo-Carranza SA, Guard B, **Gomez-Vazquez JP**, Dowd SE, Brigthsmith DJ. 2016. Comprehensive molecular characterization of bacterial communities in feces of pet birds using 16S marker sequencing. Microbial Ecology Epub ahead of print Aug 27 2016 DOI 10.1007/s00248-016-0840-7.
  
### As Consultant:  
  
  - Emery CB, Outerbridge CA, Knych HK, Lam ATH, **Gomez-Vazquez JP**, White SD. Preliminary study of the stability of dexamethasone when added to commercial veterinary ear cleaners over a 90 day period. Vet Dermatol. 2021 Feb 2. doi: 10.1111/vde.12924. Epub ahead of print. PMID: 33528860.  
  
________________________
## Participation at conferences

### Oral Presentations:

  - Spatio-Temporal analysis of the trade network of the cattle industry in California, October 2019, *GeoVet 2019, Davis, California, United States*
  - Evaluacion espacio-temporal de factores de riesgo para la ocurrencia de peste porcina clásica en Perú (Spatio-Temporal analysis for the CSF occurrence in Peru), October 2017, *“III SIEVMP (Iberoamerican society of veterinary epidemiology and preventive medicine) symposium”, Valdivia, Chile.*


### Poster presentations:

  - Identification of areas at risk for low immunity herds against Foot-and-Mouth disease virus in Ecuador using maximum entropy models, November 2018, *“International Symposium of Veterinary Epidemiology and Economics 15”, Chiang Mai, Thailand*
  - Live pig trade network modeling and prediction using Network analysis and exponential random graph models in Peru, June 2018, *25th International Pig Veterinary Society Congress”, Chongging Yuelai, China*
  - Herramientas bioinformáticas para el estudio de la microbiota intestinal” (Bioinformatics tools for gastrointestinal microbiota analysis), October 2015, *“XXVIII Congreso Nacional de Investigación en Medicina UANL” (National symposium of Medical research UANL), Monterrey N.L., Mexico*
  - Perfil metabólico de comunidades microbianas en heces de aves en cautiverio” (Metabolic profiles of pet birds microbiota), October 2015, *“4th KALAANKAB Symposium”, Villahermosa, Tabasco, Mexico*




